DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog;

\c blog;

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  user_name VARCHAR NOT NULL,
  comment VARCHAR NOT NULL,
  blog_id INTEGER NOT NULL,
  time_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
